// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrate
const Verifier = artifacts.require('verifier');
const ZProof = require("../../zokrates/code/square/proof.json");

// Test verification with correct proof

contract ('testingVerifier', accounts => {

    describe('test the tx in contract', function() {
        beforeEach(async function() {
            this.contract = await Verifier.new();
        });

        it('Test verification with correct proof', async function () {

            let status = await this.contract.verifyTx.call(
              ...Object.values(ZProof.proof), ZProof.inputs)
            
            assert.equal(status, true);
        });

        it ('Test verification with incorrect proof', async function () {

            //let difInputs =
            /*
            let a = [["0x27ff02701c19253251d30334caaedfca02a1d1a1d4f9e9006a9a1296f2b4b000","0x25ebf751053199c6343f9f93a75680f6214bbe1855503642d1391b06599ba000"],
                    [["0x0f5204c9ab7e9bc91768a0cc06aa8a0598c8f38d2ad6e4845568c349ab953000", "0x2992a0221321d1a265b55d7e8a6befc81cab7bcbbb8c5964f0a615bdd1f17000"]["0x0f5204c9ab7e9bc91768a0cc06aa8a0598c8f38d2ad6e4845568c349ab953000", "0x2992a0221321d1a265b55d7e8a6befc81cab7bcbbb8c5964f0a615bdd1f17000"]],
                    ["0x2b1e06964f48687ccb0262b55627c110d3f808e26cd2253b6e2024fbddb77000", "0x0ff66519e0cdd4a8c04b9241de23cf016d472299bad2adc987c75e50d6ffd000"]]

            */
            let b = ["0x0000000000000000000000000000000000000000000000000000000000000052",  "0x0000000000000000000000000000000000000000000000000000000000000025"];

            let status = await this.contract.verifyTx.call(
              ...Object.values(ZProof.proof), b);
            
            assert.equal(status, false);

        })

    })
})

// - use the contents from proof.json generated from zokrates steps

    
// Test verification with incorrect proof
